# Generated by Django 5.1.2 on 2025-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('whatspp_number', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=14, null=True)),
                ('location', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.CharField(blank=True, max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slide_image/')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=55, null=True)),
                ('button_name', models.CharField(blank=True, max_length=55, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('descriptin', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('descriptin', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('exchange_policy', models.TextField(blank=True, null=True)),
                ('refund_policy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteColorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('news_feed', models.CharField(blank=True, max_length=55, null=True)),
                ('news_feed_text', models.CharField(blank=True, max_length=55, null=True)),
                ('header', models.CharField(blank=True, max_length=55, null=True)),
                ('header_taxt', models.CharField(blank=True, max_length=55, null=True)),
                ('header_icon', models.CharField(blank=True, max_length=55, null=True)),
                ('slide_run_time', models.PositiveIntegerField(blank=True, null=True)),
                ('main_body', models.CharField(blank=True, max_length=55, null=True)),
                ('main_body_title', models.CharField(blank=True, max_length=55, null=True)),
                ('main_body_text', models.CharField(blank=True, max_length=55, null=True)),
                ('background', models.CharField(blank=True, max_length=55, null=True)),
                ('background_text', models.CharField(blank=True, max_length=55, null=True)),
                ('footer', models.CharField(blank=True, max_length=55, null=True)),
                ('footer_taxt', models.CharField(blank=True, max_length=55, null=True)),
                ('footer_icon', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('site_slogan', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('secondary_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('fab_icon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('copyright', models.CharField(blank=True, max_length=55, null=True)),
                ('copyright_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to='social/')),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('descriptin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
