# Generated by Django 6.0.1 on 2026-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
