# Generated by Django 6.0.1 on 2026-02-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productgifting'),
        ('site_app', '0002_landingpageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='product.product'),
        ),
    ]
