# Generated by Django 5.1.6 on 2025-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_contactinformation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
