# Generated by Django 5.1.6 on 2025-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_contactinformation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(null=True, upload_to='slide_image/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
