# Generated by Django 6.0.1 on 2026-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_landingpageproduct_main_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproduct',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
