# Generated by Django 6.0.1 on 2026-02-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_deliveryoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_option/'),
        ),
    ]
