# Generated by Django 5.1.6 on 2025-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_alter_newsfeed_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='image_url',
        ),
        migrations.AddField(
            model_name='faq_list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
