# Generated by Django 6.0.1 on 2026-02-13 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_deliveryoption_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_option/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
