# Generated by Django 6.0.1 on 2026-02-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdeliverycharge'),
        ('site_app', '0008_alter_deliveryoption_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageproduct',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
