# Generated by Django 6.0.1 on 2026-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_landingpageproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageproduct',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='landingpageproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='landingpageproduct',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='landingpageproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='landingpageproduct',
            name='variant',
        ),
        migrations.AddField(
            model_name='landingpageproduct',
            name='area_and_charge',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpageproduct',
            name='need_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
