# Generated by Django 6.0.1 on 2026-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0012_remove_landingpageproduct_delivery_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDeliveryChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_and_charge', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Delivery Charge Config',
                'verbose_name_plural': 'Global Delivery Charge Config',
            },
        ),
    ]
