# Generated by Django 6.0.1 on 2026-07-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_wishlist_unique_together_wishlist_variant_and_more'),
        ('site_app', '0013_sitedeliverychargeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='product.product'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
