# Generated by Django 6.0.1 on 2026-08-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0014_homeslider_product_alter_homeslider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='footertaglink',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='footertaglink',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
