# Generated by Django 6.0.1 on 2026-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_invoicecolorconfig_maintenancecost_dailyprofit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='extra_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='extra_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
