# Generated by Django 6.0.1 on 2026-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0018_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecost',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('utilities', 'Utilities (Electricity/Gas/Water)'), ('salary', 'Salary / Wages'), ('raw_materials', 'Raw Materials'), ('packaging', 'Packaging Materials'), ('marketing', 'Marketing / Ads'), ('equipment', 'Equipment / Machinery'), ('transport', 'Transport / Delivery'), ('maintenance_repair', 'Maintenance / Repair'), ('software', 'Software / Subscription'), ('others', 'Others')], default='others', max_length=30),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking (bKash/Nagad)'), ('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
