# Generated by Django 6.0.1 on 2026-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0019_maintenancecost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproduct',
            name='enable_pixel_tracking',
            field=models.BooleanField(default=True, help_text='If unchecked, Facebook Pixel / GTM / GA4 events for THIS landing page will NOT fire, even if global tracking is ON.'),
        ),
        migrations.AddField(
            model_name='landingpageproduct',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Optional: override the global Facebook Pixel ID for this landing page only. Leave blank to use the global one.', max_length=100, null=True),
        ),
    ]
