# Generated by Django 6.0.1 on 2026-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0020_landingpageproduct_enable_pixel_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproduct',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingpageproduct',
            name='gtm_container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
