# Generated by Django 6.0.1 on 2026-08-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_facebook_pixel_id_product_ga4_measurement_id_and_more'),
        ('site_app', '0021_landingpageproduct_ga4_measurement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page', to='product.product'),
        ),
    ]
