# Generated by Django 6.0.1 on 2026-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_alter_landingpageproduct_main_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='brand_email',
            field=models.EmailField(blank=True, default='pencilwoodbd@gmail.com', help_text='Support/contact email shown on invoices.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='brand_name',
            field=models.CharField(blank=True, default='PencilWoodBD', help_text='Main brand name. Shown in dashboard page titles, sidebar, invoice header, delivery token, OTP SMS text, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='brand_phone',
            field=models.CharField(blank=True, help_text='Phone number shown on invoices and delivery tokens (e.g. +8801855942504).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='brand_short_name',
            field=models.CharField(blank=True, default='Pencilwood', help_text='Short brand name used in tight spaces like the dashboard sidebar.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='brand_website',
            field=models.CharField(blank=True, default='www.pencilwoodbd.com', help_text='Website shown on invoices (e.g. www.example.com).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='dashboard_title',
            field=models.CharField(blank=True, default='PencilWoodBD | Online Shopping', help_text='Browser tab title shown on the main dashboard page.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='invoice_note',
            field=models.CharField(blank=True, default='Make all cheques payable to {brand_name}', help_text='Note shown on the invoice above the footer. Use {brand_name} as a placeholder if needed.', max_length=255, null=True),
        ),
    ]
