# Generated by Django 6.0.1 on 2026-09-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_facebook_pixel_id_product_ga4_measurement_id_and_more'),
        ('site_app', '0023_sitecontent_brand_email_sitecontent_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('uploaded_video', 'Uploaded Video'), ('external_link', 'External Video Link (YouTube/FB/Insta/TikTok)'), ('product_video', 'Use Existing Product Video')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='showcase/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='showcase/videos/')),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('poster_image', models.ImageField(blank=True, help_text='Thumbnail shown before video plays (optional, recommended for video_url)', null=True, upload_to='showcase/posters/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_uses', to='product.productvideo')),
            ],
            options={
                'verbose_name': 'Showcase Media (See It in Real Life)',
                'verbose_name_plural': 'Showcase Media (See It in Real Life)',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
