# Generated by Django 6.0.1 on 2026-09-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_showcasemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(help_text="Stable key used by the frontend, e.g. 'why_choose'. Cannot be changed after creation.", unique=True)),
                ('admin_label', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('builtin', 'Built-in'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('heading', models.CharField(blank=True, max_length=150, null=True)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_sections/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='about_whychooseus',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='about_whychooseus',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
