# Generated by Django 6.0.1 on 2026-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0026_seed_builtin_home_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='min_height_px',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Force an exact minimum height in pixels, e.g. 400. Leave blank to size automatically based on content.', null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='size',
            field=models.CharField(choices=[('compact', 'Compact (small padding)'), ('normal', 'Normal'), ('spacious', 'Spacious (large padding)')], default='normal', max_length=10),
        ),
    ]
