# Generated by Django 6.0.1 on 2026-09-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0027_homesection_min_height_px_homesection_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='min_height_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
