# Generated by Django 6.0.1 on 2026-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0028_alter_homesection_min_height_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
