# Generated by Django 6.0.1 on 2026-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_is_gift_only'),
        ('site_app', '0029_otpverification_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='badge_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections', to='product.category'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='content_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('product', 'Product / Category Wise')], default='banner', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='design_style',
            field=models.CharField(blank=True, choices=[('product_grid', 'Product Grid (like the main product listing)'), ('product_slider', "Product Slider (horizontal scroll, like 'Kidz Product')"), ('category_tiles', 'Category / Sub-category Tiles (shop-by-category)'), ('tabbed_products', 'Category Tabs + Products (tab-to-switch)'), ('bestseller_strip', 'Best Seller / New Arrival Strip (badge grid)'), ('banner_product_combo', 'Banner + Product Combo (banner beside products)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='item_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
