# Generated by Django 6.0.1 on 2026-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0030_homesection_badge_text_homesection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='badge_text',
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_bg_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for the text background box. Leave blank for no background.', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_bg_opacity',
            field=models.PositiveIntegerField(default=0, help_text='0 = no background, 100 = fully solid. Used with Text Background Color.'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_color',
            field=models.CharField(blank=True, default='', help_text='Hex color, e.g. #ffffff. Leave blank for default.', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_font_family',
            field=models.CharField(blank=True, choices=[('', 'Default (site font)'), ("'Sora', sans-serif", 'Sora (site default)'), ("'Hind Siliguri', sans-serif", 'Hind Siliguri (Bangla)'), ("'Poppins', sans-serif", 'Poppins'), ("'Playfair Display', serif", 'Playfair Display (elegant serif)'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Oswald', sans-serif", 'Oswald (condensed/bold)'), ("'Nunito', sans-serif", 'Nunito (rounded)')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_font_size',
            field=models.PositiveIntegerField(blank=True, help_text='Heading font size in px. Subheading is auto-scaled smaller. Leave blank for default.', null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='text_font_weight',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=10),
        ),
    ]
