# Generated by Django 6.0.1 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0031_remove_homesection_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='badge_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
