# Generated by Django 6.0.1 on 2026-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0032_homesection_badge_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='text_bg_color',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_bg_opacity',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_font_family',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_font_size',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_font_style',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='text_font_weight',
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_align',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_bg_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_bg_opacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_font_family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_italic',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='heading_weight',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_align',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_bg_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_bg_opacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_font_family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_italic',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subheading_weight',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
