# Generated by Django 6.0.1 on 2026-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0033_remove_homesection_text_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproduct',
            name='blocked_mode',
            field=models.CharField(choices=[('otp', 'OTP ON - Blocked user must verify OTP to order'), ('allow', 'OTP OFF - Allow order directly (no OTP)'), ('deny', 'OTP OFF - Do not take order, show blocked message')], default='otp', max_length=10),
        ),
    ]
