# Generated by Django 6.0.1 on 2026-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0034_landingpageproduct_blocked_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
