# Generated by Django 5.1.6 on 2025-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
