# Generated by Django 5.1.6 on 2025-04-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Draft', 'Draft'), ('Trash', 'Trash')], default='Draft', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Draft', 'Draft'), ('Trash', 'Trash')], default='Draft', max_length=25),
        ),
    ]
