# Generated by Django 6.0.1 on 2026-02-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FLAT', 'Flat'), ('FREE', 'Free')], default='FREE', max_length=30)),
                ('value', models.PositiveIntegerField(default=1)),
                ('gift_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_product', to='product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_product', to='product.product')),
            ],
        ),
    ]
