# Generated by Django 6.0.1 on 2026-02-03 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productgifting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_and_charge', models.JSONField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_charge', to='product.product')),
            ],
        ),
    ]
