# Generated by Django 5.1.6 on 2025-02-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_place',
            new_name='discount_price',
        ),
    ]
