# Generated by Django 6.0.1 on 2026-03-02 19:21

from django.db import migrations

def fill_missing_sku(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    ProductVariant = apps.get_model('product', 'ProductVariant')
    generate_product_sku = apps.get_model('product', 'Product')._meta.get_field('sku').default

    # Fill missing Product SKUs
    for product in Product.objects.filter(sku__isnull=True):
        product.sku = ''.join(__import__('random').choices('0123456789', k=6))
        product.save(update_fields=['sku'])

    # Fill missing ProductVariant SKUs
    for variant in ProductVariant.objects.filter(sku__isnull=True):
        base_sku = variant.product.sku or ''.join(__import__('random').choices('0123456789', k=6))
        sku = base_sku
        if variant.attributes:
            for key in sorted(variant.attributes.keys()):
                sku = f"{sku}-{variant.attributes[key]}"
        variant.sku = sku
        variant.save(update_fields=['sku'])

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attribute_brand_product_has_variants_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_missing_sku),
    ]
