# Generated by Django 6.0.1 on 2026-03-02 19:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20260303_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=128, blank=False, null=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=128, blank=False, null=False),
        ),
    ]
