# Generated by Django 6.0.1 on 2026-06-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('subdomain', models.CharField(help_text='cradle.pencilwoodbd.com', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('is_active', models.BooleanField(default=True)),
                ('need_otp_verified', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='landing/seo/')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok_pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gtm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('head_script', models.TextField(blank=True, null=True)),
                ('body_start_script', models.TextField(blank=True, null=True)),
                ('footer_script', models.TextField(blank=True, null=True)),
                ('facebook_access_token', models.TextField(blank=True, null=True)),
                ('facebook_test_code', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_charge', models.JSONField(blank=True, null=True)),
                ('theme_config', models.JSONField(blank=True, null=True)),
                ('order_form_config', models.JSONField(blank=True, null=True)),
                ('marketing_settings', models.JSONField(blank=True, null=True)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('total_orders', models.PositiveBigIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_main_product', to='product.product')),
                ('products', models.ManyToManyField(blank=True, related_name='landing_products', to='product.product')),
                ('upsell_products', models.ManyToManyField(blank=True, related_name='landing_upsells', to='product.product')),
            ],
        ),
    ]
