# Generated by Django 6.0.1 on 2026-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_tag_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
