# Generated by Django 6.0.1 on 2026-07-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customer_has_password_customuser_phone_and_more'),
        ('product', '0012_productvariant_is_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted', to='product.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'product', 'variant')},
        ),
    ]
