# Generated by Django 6.0.1 on 2026-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_reviewsettings_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_sold_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_global_sold_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewsettings',
            name='default_sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
