# Generated by Django 6.0.1 on 2026-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='inventory_type',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('unlimited', 'Unlimited')], default='in_stock', max_length=20),
        ),
    ]
