# Generated by Django 6.0.1 on 2026-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productvariant_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_pixel_tracking',
            field=models.BooleanField(default=True, help_text='If unchecked, Facebook Pixel / GTM / GA4 events for THIS product will NOT fire on the e-commerce site, even if global tracking is ON.'),
        ),
    ]
