# Generated by Django 6.0.1 on 2026-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_enable_pixel_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdeliverycharge',
            name='delivery_charge_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
