# Generated by Django 6.0.1 on 2026-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productdeliverycharge_delivery_charge_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gtm_container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
