# Generated by Django 6.0.1 on 2026-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_facebook_pixel_id_product_ga4_measurement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gift_only',
            field=models.BooleanField(default=False),
        ),
    ]
