# Generated by Django 6.0.1 on 2026-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(blank=True, choices=[('smtp', 'Smtp'), ('api', 'Api')], default='smtp', max_length=25, null=True)),
                ('mail_type', models.CharField(blank=True, choices=[('info', 'Info'), ('no_reply', 'No Reply'), ('contact', 'Contact'), ('career', 'Career')], default='info', max_length=25, null=True)),
                ('server', models.CharField(blank=True, max_length=50, null=True)),
                ('host_user', models.CharField(blank=True, max_length=255, null=True)),
                ('host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('tls', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl', models.BooleanField(default=False)),
                ('today_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('today_date', models.DateField(blank=True, null=True)),
                ('today_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook_pixel', 'Facebook Pixel'), ('facebook_capi', 'Facebook Capi'), ('gtm', 'Gtm'), ('ga4', 'Ga4')], max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=32)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
