# Generated by Django 5.1.6 on 2025-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(help_text='Your Facebook Pixel ID', max_length=255)),
                ('access_token', models.CharField(blank=True, help_text='Your Businuess Manager Access Token', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable Pixel tracking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
