# Generated by Django 6.0.1 on 2026-08-16 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_utmlink'),
        ('order', '0028_remove_orderrequest_click_id_and_more'),
        ('product', '0017_productvariant_inventory_type'),
        ('site_app', '0019_maintenancecost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PencilwoodKidz', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount (৳)'), ('PERCENT', 'Percentage (%)')], default='FIXED', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for PERCENT type discounts. Leave blank for FIXED or no cap.', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required for this coupon to apply.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('max_uses_per_phone', models.PositiveIntegerField(default=1, help_text='How many times a single phone number can use this coupon. E.g. 1 = once per number.')),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, help_text='Overall cap across all customers. Leave blank for unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_landing_pages', models.ManyToManyField(blank=True, help_text='Restrict this coupon to specific landing pages. Leave empty = works on ALL landing pages/website.', to='site_app.landingpageproduct')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Restrict this coupon to specific products. Leave empty = works on all products.', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usage', to='order.order')),
            ],
        ),
    ]
