# Generated by Django 6.0.1 on 2026-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='count_orders_before_coupon_creation',
            field=models.BooleanField(default=True, help_text='If unchecked, only orders placed AFTER this coupon was created count toward customer eligibility.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer_condition',
            field=models.CharField(choices=[('ANY', 'Any Customer'), ('FIRST_ORDER', 'First Order Only'), ('EXISTING', 'Existing Customer (has 1+ previous order)'), ('MIN_ORDERS', 'At Least N Previous Orders')], default='ANY', help_text='Defines which customers are eligible to use this coupon.', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_previous_orders',
            field=models.PositiveIntegerField(blank=True, help_text='Used only when Customer Condition = At Least N Previous Orders.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order_history_scope',
            field=models.CharField(choices=[('ALL_ORDERS', 'Count orders across the whole store'), ('SAME_SCOPE', "Count only orders within this coupon's Landing Page/Product")], default='ALL_ORDERS', help_text='Defines which previous orders are counted for customer eligibility.', max_length=20),
        ),
    ]
