# Generated by Django 6.0.1 on 2026-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_coupon_count_orders_before_coupon_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='count_orders_before_coupon_creation',
            field=models.BooleanField(default=True, help_text='If unchecked, only orders placed AFTER this coupon was created count toward eligibility.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customer_condition',
            field=models.CharField(choices=[('ANY', 'Any Customer'), ('FIRST_ORDER', 'First Order Only'), ('EXISTING', 'Existing Customer (has 1+ previous order)'), ('MIN_ORDERS', 'At Least N Previous Orders')], default='ANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_previous_orders',
            field=models.PositiveIntegerField(blank=True, help_text="Used only when Customer Condition = 'At Least N Previous Orders'", null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='order_history_scope',
            field=models.CharField(choices=[('ALL_ORDERS', 'Count orders across the whole store'), ('SAME_SCOPE', "Count only orders within this coupon's Landing Page/Product")], default='ALL_ORDERS', max_length=20),
        ),
    ]
