# Generated by Django 6.0.1 on 2026-09-29 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_coupon_count_orders_before_coupon_creation_and_more'),
        ('product', '0021_product_is_gift_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allow_on_landing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allow_on_website',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CouponTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='marketing.coupon')),
                ('required_products', models.ManyToManyField(related_name='coupon_tiers', to='product.product')),
            ],
        ),
    ]
