# Generated by Django 5.1.2 on 2025-02-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='admin_flag',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='flag',
        ),
    ]
