# Generated by Django 6.0.1 on 2026-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customer_phone_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Landing Page', 'Landing Page'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Referral', 'Referral'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
    ]
