# Generated by Django 6.0.1 on 2026-08-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, default='Others', max_length=100, null=True),
        ),
    ]
