# Generated by Django 6.0.1 on 2026-08-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customer_source'),
        ('order', '0030_steadfastwebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('lifetime', 'Lifetime (all-time cancel count)'), ('consecutive', 'Consecutive (back-to-back cancels, resets on delivery)')], default='lifetime', help_text="Default: Lifetime. 'Consecutive' hole kono order delivered hole counter reset hobe.", max_length=20)),
                ('cancel_threshold', models.PositiveIntegerField(default=5, help_text='Koto bar cancel hole auto-block hobe. Default: 5')),
                ('is_auto_block_enabled', models.BooleanField(default=True, help_text='Off korle auto-block hobe na, shudhu count track hobe.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Track Setting',
                'verbose_name_plural': 'Track Settings',
            },
        ),
        migrations.CreateModel(
            name='BlockedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('device_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('reason', models.CharField(choices=[('auto_cancel_limit', 'Auto: Cancel limit exceeded'), ('manual', 'Manually blocked by admin')], default='auto_cancel_limit', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_count_at_block_time', models.PositiveIntegerField(default=0)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Null hole system auto-block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP/Device',
                'verbose_name_plural': 'Blocked IPs/Devices',
                'ordering': ['-blocked_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ip_address', 'device_hash'), name='unique_active_block_per_identity')],
            },
        ),
        migrations.CreateModel(
            name='OrderTrackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('device_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status_at_capture', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_records', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Track Record',
                'verbose_name_plural': 'Order Track Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='authenticat_ip_addr_ad9106_idx'), models.Index(fields=['device_hash'], name='authenticat_device__bb665d_idx')],
            },
        ),
    ]
