# Generated by Django 6.0.1 on 2026-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_tracksettings_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksettings',
            name='scope',
            field=models.CharField(choices=[('order', 'Order-wise (count cancelled per orders) [Default]'), ('product', 'Product-wise (count cancels per individual product)')], default='order', help_text='Default: Order-wise. Order-wise hole ekta order e jotogula product e cancel thakuk na keno, seta 1 cancel hisebe count hobe. Product-wise hole prottek product er cancel count alada vabe track hobe.', max_length=20),
        ),
    ]
