# Generated by Django 6.0.1 on 2026-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_tracksettings_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedidentity',
            options={'ordering': ['-blocked_at'], 'verbose_name': 'Blocked Identity', 'verbose_name_plural': 'Blocked Identities'},
        ),
        migrations.RemoveConstraint(
            model_name='blockedidentity',
            name='unique_active_block_per_identity',
        ),
        migrations.AddField(
            model_name='blockedidentity',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordertrackrecord',
            name='is_identity_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blockedidentity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
