# Generated by Django 6.0.1 on 2026-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_blockedidentity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksettings',
            name='blocked_message',
            field=models.TextField(blank=True, default='আপনার অ্যাকাউন্ট ব্লক করা হয়েছে। অনুগ্রহ করে আমাদের সাইটে যোগাযোগ করুন।'),
        ),
        migrations.AddField(
            model_name='tracksettings',
            name='ecom_blocked_mode',
            field=models.CharField(choices=[('otp', 'OTP ON - Blocked user must verify OTP to order'), ('allow', 'OTP OFF - Allow order directly (no OTP)'), ('deny', 'OTP OFF - Do not take order, show blocked message')], default='otp', help_text='E-commerce checkout: blocked user er jonno OTP on/off. OTP = OTP diye order, Allow = OTP charai order nibe, Deny = order nibe na, message dekhabe.', max_length=10),
        ),
    ]
