# Generated by Django 6.0.1 on 2026-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_tracksettings_blocked_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
