# Generated by Django 6.0.1 on 2026-09-22 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0013_alter_blockedidentity_options_and_more'),
        ('product', '0021_product_is_gift_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('first_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('landing_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_profiles', to='authentication.customer')),
            ],
            options={
                'verbose_name': 'Visitor Profile',
                'verbose_name_plural': 'Visitor Profiles',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('category_view', 'Category View'), ('search', 'Search'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('wishlist_add', 'Wishlist Add'), ('wishlist_remove', 'Wishlist Remove'), ('checkout_start', 'Checkout Start'), ('order_placed', 'Order Placed'), ('login', 'Login'), ('signup', 'Signup'), ('custom', 'Custom')], db_index=True, default='page_view', max_length=30)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='authentication.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='product.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.visitorprofile')),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitorprofile',
            index=models.Index(fields=['customer', '-last_seen'], name='tracking_vi_custome_8eff3f_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['customer', '-created_at'], name='tracking_ac_custome_4641dd_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['visitor', '-created_at'], name='tracking_ac_visitor_1319f5_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='tracking_ac_event_t_781805_idx'),
        ),
    ]
