# Generated by Django 6.0.1 on 2026-10-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_tracksettings_blocked_message_and_more'),
        ('product', '0021_product_is_gift_only'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='variant_label',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('category_view', 'Category View'), ('variant_view', 'Variant View'), ('search', 'Search'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('wishlist_add', 'Wishlist Add'), ('wishlist_remove', 'Wishlist Remove'), ('checkout_start', 'Checkout Start'), ('order_placed', 'Order Placed'), ('login', 'Login'), ('signup', 'Signup'), ('custom', 'Custom')], db_index=True, default='page_view', max_length=30),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['product', '-created_at'], name='tracking_ac_product_eb2ef3_idx'),
        ),
    ]
