# Generated by Django 6.0.1 on 2026-02-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_uuid',
            new_name='order_id',
        ),
    ]
