# Generated by Django 5.1.2 on 2025-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Shipped', 'Shipped'), ('Ready to Ship', 'Ready to Ship'), ('Out for Delivery', 'Out for Delivery'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Return', 'Return')], default='Pending', max_length=50),
        ),
    ]
