# Generated by Django 5.1.6 on 2025-02-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('order', '0004_alter_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_address', to='authentication.customer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
