# Generated by Django 6.0.1 on 2026-02-14 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
        ('site_app', '0008_alter_deliveryoption_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='site_app.deliveryoption'),
        ),
    ]
