# Generated by Django 6.0.1 on 2026-03-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_product_name_orderitem_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
