# Generated by Django 6.0.1 on 2026-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitem_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promotions_applied',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
