# Generated by Django 6.0.1 on 2026-06-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_promotions_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_total_price',
        ),
    ]
