# Generated by Django 6.0.1 on 2026-07-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderrequest_orderrequestitem'),
        ('order', '0012_remove_orderitem_discount_total_price'),
    ]

    operations = [
    ]
