# Generated by Django 6.0.1 on 2026-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_merge_20260708_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='order/design_files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='work_assign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='order_request/design_files/'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='order_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='work_assign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
