# Generated by Django 6.0.1 on 2026-07-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_merge_20260706_0429'),
        ('order', '0014_order_advance_amount_order_design_file_and_more'),
    ]

    operations = [
    ]
