# Generated by Django 6.0.1 on 2026-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_merge_20260712_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='work_status',
            field=models.CharField(choices=[('none', 'None'), ('design', 'Design'), ('correction', 'Correction'), ('call', 'Call'), ('knock', 'Knock'), ('other', 'Other'), ('done', 'Done'), ('hold', 'Hold'), ('cancel', 'Cancel')], default='none', max_length=20),
        ),
    ]
