# Generated by Django 6.0.1 on 2026-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_orderrequest_work_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
