# Generated by Django 6.0.1 on 2026-08-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderrequest_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_packaging_item',
            field=models.BooleanField(default=False),
        ),
    ]
