# Generated by Django 6.0.1 on 2026-08-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_orderitem_is_packaging_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_packaging_item',
        ),
    ]
