# Generated by Django 6.0.1 on 2026-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Bot', help_text="Just a label, e.g. 'Order Notify Bot'", max_length=100)),
                ('bot_token', models.CharField(max_length=255)),
                ('group_chat_id', models.CharField(help_text='e.g. -1001234567890', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_sources', models.JSONField(blank=True, default=list, help_text='List of ORDER_SOURCE values that should trigger a Telegram notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot Config',
                'verbose_name_plural': 'Telegram Bot Configs',
            },
        ),
    ]
