# Generated by Django 6.0.1 on 2026-08-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_telegrambotconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Landing Page', 'Landing Page'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Referral', 'Referral'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Landing Page', 'Landing Page'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Referral', 'Referral'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
    ]
