# Generated by Django 6.0.1 on 2026-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_orderrequest_click_id_orderrequest_landing_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='click_id',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='landing_url',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='utm_source',
        ),
        migrations.AddField(
            model_name='order',
            name='click_id',
            field=models.CharField(blank=True, help_text='fbclid / ttclid / gclid', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='landing_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
