# Generated by Django 6.0.1 on 2026-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_coupon_order_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadFastWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('delivery_status', 'Delivery Status'), ('tracking_update', 'Tracking Update')], max_length=100, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('tracking_message', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
