# Generated by Django 6.0.1 on 2026-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_steadfastwebhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
