# Generated by Django 6.0.1 on 2026-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_while_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
