# Generated by Django 6.0.1 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_placed_while_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
