# Generated by Django 6.0.1 on 2026-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_orderattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='upazila',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
