# Generated by Django 6.0.1 on 2026-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_order_created_by_order_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow Up'), ('confirmed', 'Confirmed'), ('token_print', 'Token Print'), ('ready_to_ship', 'Ready To Ship'), ('parcel_created', 'Parcel Created'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='new', max_length=50),
        ),
    ]
