# Generated by Django 6.0.1 on 2026-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
